config/routes.rb
Read::Application.routes.draw do

 
  devise_for :users
  resources :users
  resources :books
  resources :books, :users do
    resources :reviews, :only => [:create, :destroy]
    
  end

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  root  'static_pages#home'

  

end

app/models/book.rb
class Book < ActiveRecord::Base
	attr_accessible :title, :isbn, :author, :content

	has_many :reviews
	
	# has_many :reviewers, :class_name => "User", :through => :reviews

end

app/models/review.rb
class Review < ActiveRecord::Base
	attr_accessible :content
	
	default_scope -> { order('created_at DESC') }
	belongs_to :user
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :name
  

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :signed_in_user

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
    @review_all = @book.reviews
    @reviews = @book.reviews.paginate(page: params[:page])
    #@user = User.find(params)
  end

  def index
    @books = Book.paginate(page: params[:page])
  end
  

  def update
    @book = Book.find(params[:id])
    @review = Review.new
    
    respond_to do |format|
      if @book.update_attributes(book_params)
        @review.content = @book.content
        @review.book_id = @book.id
        @review.user_id = current_user.id if user_signed_in?
        @review.save
        Book.update(@book.id, :content => '')
        @book.update_attributes(book_params)
        format.html { redirect_to @book }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  private

  def signed_in_user
      redirect_to new_user_session_path , notice: "Please sign in." unless signed_in?
    end

  def book_params
    params.require(:book).permit(:title, :author, :isbn, :content)
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  	@book = Book.find_using_slug(params[:book_id])
  	@review = Review.new
  	@review.book_id = @book.id
  end

  def create
  	@book = Book.find(params[:id])
  	@review = Review.new(review_params)
     @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = "review created!"
      redirect_to root_url
    else
      render 'static_pages/home'
  	end
  end


  def destroy
  end

  private

  def review_params
  	params.require(:review).permit(:content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@user = User.find(current_user.id)
  end

  def help
  end

  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def show
  	@user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page])
  end

  def index
  	@users = User.paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Greed to Read"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
	def gravatar_for_book(book, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(book.title.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: book.title, class: "gravatar")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for_user(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<% provide(:title, 'Edit book') %>
<h1>Edit a book</h1>

<div class="row">
  <div class="span6 offset3">

<%= form_for(@book) do |f| %>
  

  <%= render 'shared/books_error_messages'%>
	
  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :ISBN_No %><br />
  <%= f.number_field :isbn %></div>

  <div><%= f.label :author %><br />
  <%= f.text_field :author %></div>

  <%= gravatar_for_book @book %>
  <a href="http://gravatar.com/emails">change</a>

  <div><%= f.submit "Change", class: "btn btn-small btn-primary" %></div>
<% end %>


 </div>
</div>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<h1>All books</h1>

<%= will_paginate %>

<ul class="users">
  <% @books.each do |book| %>
     <li>
      
      <%= link_to book.title, book %>
    </li>

  <% end %>
</ul>

<%= will_paginate %>

app/views/books/new.html.erb
<% provide(:title, 'Add a book') %>
<h1>Add a book</h1>

<div class="row">
  <div class="span6 offset3">

<%= form_for(@book) do |f| %>
  

  <%= render 'shared/books_error_messages'%>
	
  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :ISBN_No %><br />
  <%= f.number_field :isbn %></div>

  <div><%= f.label :author %><br />
  <%= f.text_field :author %></div>

  <div><%= f.submit "Add", class: "btn btn-small btn-primary" %></div>
<% end %>


 </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.title)%>


  <div class="row">
    <aside class="span4">
      <%= gravatar_for_book @book %><%= @book.isbn %>, <%= @book.title %>, <%= @book.author %>
      <br>
      <%= link_to "Edit", edit_book_path %>
      <section>
        <%= render 'shared/review_form' %>
      </section>
    </aside>
  

  <div class="span8">
    <% if @book.reviews.any? %>
      <h3>Reviews (<%= @book.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
    <% end %>
  </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Gread",   root_path %>
    by <a href="https://www.facebook.com/devangtgr8">Devang Gupta</a>
     and <a href="https://www.facebook.com/shivamsatija04">Shivam Satija</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Gread", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to "Home", current_user %></li>
          <% else %>
          <li><%= link_to "Home", root_path %></li>
          <%end%>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
	<div>
		<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= render 'layouts/header' %>
	
		<div class="container">

			<%= yield %>

		</div>

		<%= render 'layouts/footer' %>

		<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/reviews/_review.html.erb
<li>
	<%= gravatar_for_user User.find(review.user_id) %>
	<%= link_to User.find(review.user_id).name,  User.find(review.user_id) %> review for <%= link_to Book.find(review.book_id).title, Book.find(review.book_id) %>
        
  <span class="content"><%= review.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
  </span>
</li>

app/views/shared/_books_error_messages.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb

<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_review_form.html.erb
<%= form_for(@book) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new review..." %>
  </div>
  
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for_user(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Contact Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>

  <% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
        <%= @user.reviews.count %> reviews
      </section>

      
    </aside>
  </div>

  <%else %>

  	<div class="center hero-unit">
    	<h1>Greed to Read</h1>
    	<h2>Review.Rate.Recommend</h2>
       
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
      <% end %>
  
    	
    </div>

    <%end%>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      
  
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<aside>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for_user @user %>
        <%= @user.name %>
        <h5>
        <%= @user.reviews.count %> reviews
        </h5>
      </h1>
      
    </section>

<div class="btn-group">
  <button type="button" class="btn"><%= link_to "Books", books_path %></button>
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "Add a new Book", new_book_path %></li>
    <li><%= link_to "Add a Book to your read collection", new_book_path %></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>
</aside>
<div class="span8">
    <% if @user.reviews.any? %>
      <h3>Reviews (<%= @user.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
    <% end %>
  </div>
</div>